using System.Net;
using System.Net.Http.Headers;
using System.Text;

namespace ReplicaGuard.Infrastructure.Hosters.SendCm;

/// <summary>
/// Custom multipart/form-data implementation used for compatibility with
/// third-party upload endpoints that do not correctly handle RFC-compliant
/// filename encoding generated by .NET's MultipartFormDataContent.
///
/// The target service stores the MIME-encoded value from the `filename`
/// parameter (e.g. =?utf-8?B?...?=) instead of decoding it or honoring
/// the RFC 5987 `filename*` parameter. As a result, non-ASCII filenames
/// are uploaded with corrupted names.
///
/// This content implementation emits the multipart payload manually and
/// writes the raw UTF-8 filename directly into the Content-Disposition
/// header, matching browser behavior and ensuring correct filename
/// preservation on the remote service.
///
/// The implementation also streams file content directly to the outgoing
/// request stream to avoid buffering large files in memory.
/// </summary>
internal sealed class RawMultipartFormDataContent : HttpContent
{
    private readonly string _boundary;
    private readonly IReadOnlyDictionary<string, string> _fields;
    private readonly Stream _fileStream;
    private readonly string _fileName;
    private readonly string _contentType;

    public RawMultipartFormDataContent(
        IReadOnlyDictionary<string, string> fields,
        Stream fileStream,
        string fileName,
        string contentType = "application/octet-stream")
    {
        _boundary = $"----WebKitFormBoundary{Guid.NewGuid():N}";
        _fields = fields;
        _fileStream = fileStream;
        _fileName = fileName;
        _contentType = contentType;

        Headers.ContentType =
            MediaTypeHeaderValue.Parse(
                $"multipart/form-data; boundary={_boundary}");
    }

    protected override async Task SerializeToStreamAsync(
        Stream stream,
        TransportContext? context)
    {
        await using var writer =
            new StreamWriter(stream, Encoding.UTF8, leaveOpen: true);

        foreach (var field in _fields)
        {
            await writer.WriteAsync($"--{_boundary}\r\n");
            await writer.WriteAsync(
                $"Content-Disposition: form-data; name=\"{field.Key}\"\r\n\r\n");
            await writer.WriteAsync(field.Value);
            await writer.WriteAsync("\r\n");
        }

        await writer.WriteAsync($"--{_boundary}\r\n");
        await writer.WriteAsync(
            $"Content-Disposition: form-data; name=\"my_file\"; filename=\"{_fileName}\"\r\n");
        await writer.WriteAsync(
            $"Content-Type: {_contentType}\r\n\r\n");

        await writer.FlushAsync();

        await _fileStream.CopyToAsync(stream);

        await writer.WriteAsync("\r\n");
        await writer.WriteAsync($"--{_boundary}--\r\n");
        await writer.FlushAsync();
    }

    protected override bool TryComputeLength(out long length)
    {
        length = -1;
        return false;
    }
}
