<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ReplicaGuard.Domain</RootNamespace>
    <AssemblyName>ReplicaGuard.Domain</AssemblyName>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ReplicaGuard.Contracts\ReplicaGuard.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ReplicaGuard.Domain.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
