<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ReplicaGuard.Domain</RootNamespace>
    <AssemblyName>ReplicaGuard.Domain</AssemblyName>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ReplicaGuard.Contracts\ReplicaGuard.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReplicaGuard.Domain.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
